# Generated by Django 2.0.2 on 2018-02-21 13:51

import django.db.models.deletion
import django.utils.timezone
import markupfield.fields
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("slug", models.SlugField(verbose_name="URL slug")),
                (
                    "description",
                    markupfield.fields.MarkupField(
                        rendered_field=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_markup_type",
                    models.CharField(
                        choices=[
                            ("", "--"),
                            ("html", "HTML"),
                            ("plain", "Plain"),
                            ("markdown", "Markdown"),
                            ("restructuredtext", "Restructured Text"),
                        ],
                        default="markdown",
                        max_length=30,
                    ),
                ),
                ("_description_rendered", models.TextField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "slug",
                    models.SlugField(unique_for_date="date", verbose_name="URL slug"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Date",
                    ),
                ),
                (
                    "summary",
                    markupfield.fields.MarkupField(
                        rendered_field=True,
                        verbose_name="Summary",
                    ),
                ),
                (
                    "summary_markup_type",
                    models.CharField(
                        choices=[
                            ("", "--"),
                            ("html", "HTML"),
                            ("plain", "Plain"),
                            ("markdown", "Markdown"),
                            ("restructuredtext", "Restructured Text"),
                        ],
                        default="markdown",
                        max_length=30,
                    ),
                ),
                (
                    "body",
                    markupfield.fields.MarkupField(
                        rendered_field=True,
                        verbose_name="Text",
                    ),
                ),
                ("_summary_rendered", models.TextField(editable=False)),
                (
                    "body_markup_type",
                    models.CharField(
                        choices=[
                            ("", "--"),
                            ("html", "HTML"),
                            ("plain", "Plain"),
                            ("markdown", "Markdown"),
                            ("restructuredtext", "Restructured Text"),
                        ],
                        default="markdown",
                        max_length=30,
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        height_field="height",
                        upload_to="posts/%Y/%m/%d/",
                        verbose_name="Image",
                        width_field="width",
                    ),
                ),
                ("_body_rendered", models.TextField(editable=False)),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Image Height",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Image Width",
                    ),
                ),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5",
                        editable=False,
                        max_length=20,
                        verbose_name="Image PPOI",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.Category",
                        verbose_name="Category",
                    ),
                ),
            ],
        ),
    ]
