# Generated by Django 2.0.2 on 2018-03-06 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_auto_20180221_2311"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={
                "ordering": ("-date",),
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
    ]
