[tool.isort]
profile = "black"

[tool.ruff]
ignore = [
  "D211",
  "D212",
  "D10",
  "ANN",
  "RUF012",
  "PTH",
  "EM101",
  "S105",
  "ARG001",
  "ARG002",
  "PT",
  "PLR2004",
  "TRY003"
]
output-format = "github"
select = ["ALL"]

[tool.ruff.mccabe]
max-complexity = 16
